get http://localhost:3000

### Register route
post http://localhost:3000/register
Content-Type: application/json

{
  "username": "Darryl",
  "password": "",
  "confirmPassword": "hey"
}

### Login route
post http://localhost:3000/login
Content-Type: application/json

{
  "username": "newme",
  "password": "ass",
  "confirmPassword": null
}